[theme]
base = "dark"
backgroundColor = "#0e0e0e"
secondaryBackgroundColor = "#181818"
primaryColor = "#CD853F"
textColor = "#F0EBE3"
font = "sans serif"

[client]
showErrorDetails = false
toolbarMode = "viewer"

[server]
headless = true

[browser]
gatherUsageStats = false
