[connections.postgresql]
dialect = "postgresql"
driver = "psycopg2"
host = "ep-bitter-firefly-aqw6p7rq.c-8.us-east-1.aws.neon.tech"
port = 5432
database = "neondb"
username = "neondb_owner"
password = "npg_OpGHYl9dCF1I"
